export const SET_SELECTION = 'SET_SELECTION';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const ADD_BREAK = 'ADD_BREAK';
export const REMOVE_BREAK = 'REMOVE_BREAK';
export const SET_NEW_PROPERTY = 'SET_NEW_PROPERTY';

